examples/payment.py - change from_id to sender_id
LonamiWebs/Telethon pull request #1580
Opened 2020-10-03 16:38 UTC by apepenkov

2020-10-03 19:27 UTC, Lonami commented
The "right" way to make pull requests is to `git checkout` the commit prior to any changes you make (normally `master` but since you've made commits you need to `checkout` an older version). Then you `git checkout -b newbranch` to create a new **b**ranch and change to it. There you can make commits specific to a certain change set (for instance, change `from_id` to `sender_id`). When pushing and trying to send a PR, GitHub will let you choose the branch.

To "fix" this pull request you can `git revert b24aa6a` which will make a new commit reverting that and then push. I will squash it so it will look like one correct commit.

2020-10-03 19:28 UTC, Lonami requested changes

2020-10-03 19:28 UTC, Lonami commented on telethon/tl/custom/button.py
> +        return types.KeyboardButtonCallback(text, data, requires_password)
Please remove the changes in this file with the instructions given in https://github.com/LonamiWebs/Telethon/pull/1580#issuecomment-703153566.

2020-10-03 19:32 UTC, apepenkov commented
Thank you. I did it via GH Web, not via git. This is ultra OT, but do you know any good git guide? Ones Ive found were either oversimplified, or overcompicated.

2020-10-04 08:14 UTC, apepenkov commented
I'll reopen later properly xD

2020-10-04 08:14 UTC, closed without merging