WIP: Use `tg_file_id` for handling `file_id` stuff.
LonamiWebs/Telethon pull request #1622
Opened 2020-11-07 22:09 UTC by luckydonald

Work in progress for #1613.

2020-11-08 10:23 UTC, Lonami requested changes
Looks alright except for some style nits (as with most PRs; style would be less of an issue if I used [`black`](https://pypi.org/project/black/)…).

2020-11-08 10:23 UTC, Lonami commented on telethon/utils.py
> +    # end if
Telethon's codebase doesn't really use this style of comments, so I think it's better to remove them.

2020-11-08 10:23 UTC, Lonami commented on telethon/utils.py
> +    assert isinstance(file, PhotoFileId)
I think I'd rather have this `return None` if it's not a photo:

```suggestion
    if not isinstance(file, PhotoFileId):
        return None
```

2020-11-08 10:24 UTC, Lonami commented on telethon/utils.py
> +    foto_size = file.photosize
Let's make this a bit more readable and give this an actual English name (and change the uses below too):

```python
    photo_type = 's' if file.id or file.access_hash else 'x' 
    photo_size = file.photosize
    if isinstance(photo_size, (
        PhotoFileId.PhotosizeSourceLegacy,
        PhotoFileId.PhotosizeSourceThumbnail,
        PhotoFileId.PhotosizeSourceDialogPhotoSmall,
        PhotoFileId.PhotosizeSourceDialogPhotoBig,
        PhotoFileId.PhotosizeSourceStickersetThumbnail,
    )):
```

2020-11-08 19:01 UTC, Lonami commented on setup.py
> +            # requirements files see:
The link is fine, but I think this is unnecessary. We're not here to teach others how to write a `setup.py` file.

2021-01-26 20:12 UTC, Lonami commented
Closing since I think we settled we're not going to add this? Licensing and stuff IIRC.

2021-01-26 20:12 UTC, closed without merging

2021-01-27 15:58 UTC, luckydonald commented
:/

Thanks @danog.

2021-01-27 17:41 UTC, Lonami commented
To be fair it shouldn't be hard to reverse engineer the format with a Bot API bot, sending and receiving all media types, and printing the results both in Telethon and the bot API to compare how things match up. Doing so would enable us to produce a new clean implementation. I personally haven't had the time or interest to do so, but if you do, feel free to open another PR.

I also haven't looked super hard at licensing compatibility or what it entails. It might actually be fine to merge this, but IANAL.