Update thumbnail information
LonamiWebs/Telethon pull request #1679
Opened 2021-01-23 22:42 UTC by Qwerty-Space

2021-01-23 22:42 UTC, Qwerty-Space commented
I'm not actually sure what's going on with the resizing, so I'll remove that part

2021-01-23 23:18 UTC, Lonami requested changes

2021-01-23 23:18 UTC, Lonami commented on telethon/client/uploads.py
> +                file's dimensions using either ``hachoir`` or
Shouldn't this say "video dimensions"?

2021-01-23 23:18 UTC, Lonami commented on telethon/client/uploads.py
> +                file's dimensions using either ``hachoir`` or
I'm not a fan of "using `hachoir`". Users don't use this directly, it just needs to be installed.

2021-01-23 23:18 UTC, Lonami commented on telethon/client/uploads.py
> +                :tl:`DocumentAttributesVideo`.
Maybe better indicate that this should go in the list of `attributes`. Perhaps the examples section could be extended.

2021-01-26 20:10 UTC, closed without merging

2021-01-27 22:19 UTC, Qwerty-Space commented
Fixed in 9a6bc5ae72cbdeb15d9ac97b68bf7e8bab55ec0a