Try of Layer Update, remove bot file support and many more
LonamiWebs/Telethon pull request #3072
Opened 2021-06-11 14:19 UTC by New-dev0

- **Tried To Update Layer to 129**
     - Not Sure, if i Missed it somewhere.

-  **Removed Bot File Id Support**
      - As it is Wish list of Version 2
        and Telegram have changed attributes of `PhotoSize`, which was including that funcs.
        if you wish to have that, It will be  Great, if you will re-add it back, as according to layer 129.

- **Added friendly method, related to Voice Calls, for Admins or creator**
       - `modify_groupcall`
       - There are many Methods & stuff to do with Voice Calls.
       - So, I have tried to pack them in one method.
        - It will Great, if you want to suggest/change a Method Name.

- **Added missing thumb parameter to send_messages and edit_messages**

- **Added Friendly Method to Get `ChannelParticipant`**
     - `get_participant`

- **Now, we can download photo, of MessageActionEditChatPhoto with**
     -  `message.download_media`

2021-06-11 16:25 UTC, New-dev0 commented
@Lonami , are stuff fine ?

2021-06-12 08:06 UTC, Lonami requested changes
Thank you for the effort put into this! Unfortunately, there's a lot of unrelated changes in a single PR, which makes it hard to merge those I agree with.

The layer update and corrections to the code are okay, but the addition of new methods would be better left as a separate PR (although there are some issues, see comments). The removal of functionality is not something we can afford across [minor versions]([url](https://semver.org/)).

I think we should close this and open a new PR with only the desired changes (layer update, code update to work on the new layer, and maybe the errors). You can do this by creating a new [`git branch`](https://git-scm.com/docs/git-branch) from a commit *without* the changes, and then [`git cherry-pick`](https://git-scm.com/docs/git-cherry-pick) the commits we *do* want to merge.

2021-06-12 08:06 UTC, Lonami commented on telethon/client/chats.py
> +        if method == "create":
`modify_groupcall` works very unlike any other method in the library, which I don't think is a good fit. The raw API methods used here seem to also be very simple -- perhaps how to do this stuff should instead live in the wiki?

2021-06-12 08:06 UTC, Lonami commented on telethon/client/messages.py
> +                force_document=force_document,thumb=thumb,
```suggestion
                force_document=force_document, thumb=thumb,
```

2021-06-12 08:06 UTC, Lonami commented on telethon/client/uploads.py
> -                media = utils.get_input_media(bot_file)
Again, technically a breaking change since it's a loss of functionality.

2021-06-12 08:06 UTC, Lonami commented on telethon/tl/custom/file.py
> -    def id(self):
Breaking change. Even if the file IDs are unusable, people may be using them to store / refer to files.

2021-06-12 08:06 UTC, Lonami commented on telethon/utils.py
> -def resolve_bot_file_id(file_id):
Breaking change.

2021-06-12 08:06 UTC, Lonami commented on telethon/utils.py
> -def pack_bot_file_id(file):
Breaking change.

2021-06-12 08:48 UTC, New-dev0 commented
Ok, closing This and will try to Implement.

2021-06-12 08:48 UTC, closed without merging

2021-06-12 12:15 UTC, Lonami commented
Thank you. If you struggle with the `git` commands, you could always just copy-paste the relevant changes.