change in user profile buttons
LonamiWebs/Telethon pull request #3680
Opened 2022-01-24 22:47 UTC by SpEcHiDe

2022-01-25 03:28 UTC, Kedarnath101 commented
sending a Button of KeyboardButtonUserProfile changes to `KeyboardButton` with the `text provided.`
while on Sending `InputKeyboardButtonUserProfile`, It changes to `KeyboardButtonUserProfile.`

So, actually they are not type of button you can send, Its is given as output/return type of Input buttons. 
Also bot api docs mention only of inline keyboard button of user mentions

2022-01-26 09:17 UTC, Lonami requested changes
I think it would be a better idea to provide a new `.inline_mention` method. `.mention(True, 'text')` seems a bit strange.

2022-02-16 10:28 UTC, Lonami commented
@SpEcHiDe what do you think about my suggested approach https://github.com/LonamiWebs/Telethon/pull/3680#pullrequestreview-863276502?

2022-02-18 09:40 UTC, SpEcHiDe commented
@Lonami can you review once more, please?

2022-02-18 10:36 UTC, SpEcHiDe commented on telethon/types/_custom/button.py
> +                 whether to create inline / keyboard buttons
sorry, again.

Can you check once more?

2022-03-02 11:59 UTC, merged