MTProtoSender: Dont try to reconnenct in background when auto_reconnect is not available
LonamiWebs/Telethon pull request #4350
Opened 2024-04-16 18:52 UTC by JavadZahedi

I made this PR to fix this issue:
https://github.com/LonamiWebs/Telethon/issues/4092

2024-04-17 19:18 UTC, Lonami requested changes
`_start_reconnect` is called from separate tasks. Raising the error there won't let you catch it, and the library will appear to freeze.

Please make sure to try out the changes before I accept. You can edit the code to randomly force an error (maybe check when a file exists, and create the file to trigger it), for example, and see if it works as expected.

2024-12-14 19:52 UTC, xximwon approved these changes

2024-12-15 22:01 UTC, xximwon approved these changes

2025-02-26 19:04 UTC, derockspace approved these changes
Merge pull request for #4350 MTprotosender.py

2026-02-21 21:24 UTC, Lonami commented
Hi, I'm growing tired of GitHub, so I intend to move to https://codeberg.org/Lonami/Telethon. If the issue still matters to you, please reopen it there. Thanks.

2026-02-21 21:24 UTC, closed without merging